apiVersion: v1
kind: Namespace
metadata:
  name: vcluster-dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster-dev
  namespace: vcluster-dev
spec:
  releaseName: vcluster-dev
  chart:
    spec:
      chart: vcluster
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: vcluster-repo
        namespace: flux-system
  values:
    syncer:
      extraArgs:
        - --tls-san=vcluster-dev.vcluster-dev.svc.cluster.local
        - --out-kube-config-server=https://vcluster-dev.vcluster-dev.svc.cluster.local

