apiVersion: vcluster.loft.sh/v1
kind: VirtualCluster
metadata:
  name: vcluster-dev
  namespace: vcluster-dev
spec:
  replicas: 1
  chart:
    repository: https://charts.loft.sh
    name: vcluster
    version: 0.15.0
  values:
    syncer:
      extraArgs:
        - --tls-san=vcluster-dev.vcluster-dev.svc.cluster.local
        - --out-kube-config-server=https://vcluster-dev.vcluster-dev.svc.cluster.local

