apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-team-b
  namespace: flux-system
spec:
  interval: 1m
  releaseName: env-team-b
  targetNamespace: env-team-b
  chart:
    spec:
      chart: vcluster
      version: 0.22.0
      sourceRef:
        kind: HelmRepository
        name: loft-sh
  install:
    createNamespace: true
  values:
    syncer:
      extraArgs:
        - --tls-san=env-team-b.env-team-b.svc.cluster.local
        - --out-kube-config-server=https://env-team-b.env-team-b.svc.cluster.local

