apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-team-d  # ✅ Use fixed name, not a variable
  namespace: flux-system
spec:
  interval: 1m
  releaseName: env-team-d
  targetNamespace: env-team-d
  chart:
    spec:
      chart: vcluster-eks
      version: 0.22.0
      sourceRef:
        kind: HelmRepository
        name: loft-sh
  install:
    createNamespace: true
  values:
    syncer:
      extraArgs:
        - --tls-san=env-team-a.env-team-a.svc.cluster.local
        - --out-kube-config-server=https://env-team-a.env-team-a.svc.cluster.local

