apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-team-a  # ✅ Use fixed name, not a variable
  namespace: flux-system
spec:
  interval: 1m
  releaseName: env-team-a
  targetNamespace: env-team-a
  chart:
    spec:
      chart: vcluster
      version: 0.22.0
      sourceRef:
        kind: HelmRepository
        name: loft-sh
  install:
    createNamespace: true
  values:
    controlPlane:
      distro:
        k8s:
          version: v1.32.0

