apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 1h
  url: https://fluxcd-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  releaseName: flux
  interval: 5m
  chart:
    spec:
      chart: flux2
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: fluxcd
        namespace: flux-system
  values:
    gitRepository:
      url: https://github.com/<your-username>/flux-vcluster-gitops.git
      branch: main
    syncInterval: 1m

