apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vcluster
  namespace: vcluster
spec:
  interval: 5m
  timeout: 10m
  releaseName: vcluster
  chart:
    spec:
      chart: vcluster
      version: "0.22.0"
      sourceRef:
        kind: HelmRepository
        name: loftlabs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    sync:
      nodes: false
      services: true
      configMaps: true
    service:
      type: ClusterIP
