apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster-team-b
  namespace: flux-system
spec:
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./clusters/vcluster"
  wait: true
  postBuild:
    substitute:
      env: team-b  # ✅ Replace for team-b

